import type { ContributionDay } from "./types";

const CELL_SIZE = 10;
const CELL_GAP = 3;
const GRID_LEFT = 28;
const GRID_TOP = 22;
const GRID_ROWS = 7;
const CHART_PADDING_RIGHT = 18;
const CHART_PADDING_BOTTOM = 16;
const LEVEL_COLORS = ["#ebedf0", "#9be9a8", "#40c463", "#30a14e", "#216e39"];
const MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function escapeXml(text: string): string {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function monthFromDateText(dateText: string): number {
  const month = Number.parseInt(dateText.slice(5, 7), 10);
  return month - 1;
}

function buildMonthLabels(days: ContributionDay[]): Array<{ month: string; x: number }> {
  const labels: Array<{ month: string; x: number }> = [];
  let lastMonth = -1;

  for (const day of days) {
    if (day.dayOfWeek !== 0) {
      continue;
    }

    const monthIndex = monthFromDateText(day.date);
    if (monthIndex === lastMonth) {
      continue;
    }

    lastMonth = monthIndex;
    labels.push({
      month: MONTH_NAMES[monthIndex],
      x: GRID_LEFT + day.weekIndex * (CELL_SIZE + CELL_GAP),
    });
  }

  return labels;
}

export function renderContributionSvg(username: string, days: ContributionDay[]): string {
  if (days.length === 0) {
    throw new Error("Cannot render SVG without contribution data.");
  }

  const maxWeekIndex = days.reduce((max, day) => Math.max(max, day.weekIndex), 0);
  const chartWidth = GRID_LEFT + (maxWeekIndex + 1) * (CELL_SIZE + CELL_GAP) + CHART_PADDING_RIGHT;
  const chartHeight = GRID_TOP + GRID_ROWS * (CELL_SIZE + CELL_GAP) + CHART_PADDING_BOTTOM;
  const escapedUsername = escapeXml(username);

  const monthLabels = buildMonthLabels(days)
    .map((label) => `<text x="${label.x}" y="14" class="month">${label.month}</text>`)
    .join("");

  const dayLabels = [
    `<text x="0" y="${GRID_TOP + (CELL_SIZE + CELL_GAP) * 1 + 8}" class="day">Mon</text>`,
    `<text x="0" y="${GRID_TOP + (CELL_SIZE + CELL_GAP) * 3 + 8}" class="day">Wed</text>`,
    `<text x="0" y="${GRID_TOP + (CELL_SIZE + CELL_GAP) * 5 + 8}" class="day">Fri</text>`,
  ].join("");

  const dayCells = days
    .map((day) => {
      const x = GRID_LEFT + day.weekIndex * (CELL_SIZE + CELL_GAP);
      const y = GRID_TOP + day.dayOfWeek * (CELL_SIZE + CELL_GAP);
      const title = `${day.date}: ${day.count} contribution${day.count === 1 ? "" : "s"}`;
      return `<rect width="${CELL_SIZE}" height="${CELL_SIZE}" x="${x}" y="${y}" rx="2" ry="2" fill="${
        LEVEL_COLORS[day.level]
      }" data-date="${day.date}" data-count="${day.count}" data-level="${day.level}"><title>${escapeXml(
        title,
      )}</title></rect>`;
    })
    .join("");

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${chartWidth}" height="${chartHeight}" viewBox="0 0 ${chartWidth} ${chartHeight}" role="img" aria-labelledby="dailygreen-title dailygreen-desc">
  <title id="dailygreen-title">${escapedUsername}&apos;s GitHub contributions</title>
  <desc id="dailygreen-desc">Contribution chart generated by dailygreen.</desc>
  <style>
    .month,.day{font:10px -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;fill:#57606a}
  </style>
  ${monthLabels}
  ${dayLabels}
  ${dayCells}
</svg>`;
}
